language: python
python:

  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

script:
  - coverage run --omit=*.virtualenvs*,*virtualenv* example/test_package.py test
  - coverage run --omit=*.virtualenvs*,*virtualenv* example/test_local.py test
  - pytest tests/
  

after_success:
  - coveralls
  - codecov

sudo: enabled
dist: trusty
